-- Personal Context Memory tables for Supabase.

create extension if not exists pgcrypto;

create table if not exists personal_context_rules (
  id bigint generated by default as identity primary key,
  user_id text not null,
  rule_name text not null,
  rule_type text not null,
  rule_value jsonb not null,
  contact_id text,
  topic text,
  action text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists approvals (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  contact_id text,
  original_message text not null,
  generated_reply text not null,
  decision text not null default 'require_approval',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reason text,
  matched_rules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists user_statuses (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null default 'available'
    check (status in (
      'available',
      'busy',
      'unavailable',
      'traveling',
      'in_meeting',
      'do_not_disturb'
    )),
  status_reason text,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists personal_context_rules_user_idx
  on personal_context_rules (user_id);

create index if not exists personal_context_rules_active_idx
  on personal_context_rules (is_active);

create index if not exists approvals_user_idx
  on approvals (user_id);

create index if not exists approvals_status_idx
  on approvals (status);

create index if not exists user_statuses_user_idx
  on user_statuses (user_id);

create index if not exists user_statuses_active_idx
  on user_statuses (is_active);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists personal_context_rules_updated_at
  on personal_context_rules;

create trigger personal_context_rules_updated_at
before update on personal_context_rules
for each row execute function set_updated_at();

drop trigger if exists approvals_updated_at
  on approvals;

create trigger approvals_updated_at
before update on approvals
for each row execute function set_updated_at();

drop trigger if exists user_statuses_updated_at
  on user_statuses;

create trigger user_statuses_updated_at
before update on user_statuses
for each row execute function set_updated_at();
