-- Activity logging tables used by the daily report endpoint.

create table if not exists message_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  direction text not null check (direction in ('received', 'incoming', 'inbound', 'sent', 'outgoing', 'outbound')),
  message text,
  channel text default 'whatsapp',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists agent_activity_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  action_category text,
  action_type text,
  status text not null,
  mode text,
  requires_approval boolean,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists approval_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  approval_request_id bigint,
  action_category text,
  status text not null check (status in ('pending', 'approved', 'rejected')),
  original_message text,
  generated_reply text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists high_risk_alerts (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  risk_level text not null default 'high',
  action_category text,
  status text not null default 'open',
  message text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists reminder_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  reminder_text text not null,
  remind_at timestamptz,
  status text not null default 'created',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists scheduled_message_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  message text not null,
  scheduled_for timestamptz,
  status text not null default 'scheduled',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists rag_access_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  file_id text,
  file_name text,
  file_path text,
  query text,
  access_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists personal_context_decision_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  contact_id text,
  decision text not null,
  reason text,
  matched_rules jsonb not null default '[]'::jsonb,
  original_message text,
  final_action text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Keep this migration safe to re-run if a table was created earlier with a
-- partial schema. Supabase skips `create table if not exists` for existing
-- tables, so required columns must be added explicitly before indexes/logging.
alter table message_logs add column if not exists user_id text;
alter table message_logs add column if not exists contact_id text;
alter table message_logs add column if not exists direction text;
alter table message_logs add column if not exists message text;
alter table message_logs add column if not exists channel text default 'whatsapp';
alter table message_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table message_logs add column if not exists created_at timestamptz not null default now();

alter table agent_activity_logs add column if not exists user_id text;
alter table agent_activity_logs add column if not exists contact_id text;
alter table agent_activity_logs add column if not exists action_category text;
alter table agent_activity_logs add column if not exists action_type text;
alter table agent_activity_logs add column if not exists status text;
alter table agent_activity_logs add column if not exists mode text;
alter table agent_activity_logs add column if not exists requires_approval boolean;
alter table agent_activity_logs add column if not exists description text;
alter table agent_activity_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table agent_activity_logs add column if not exists created_at timestamptz not null default now();

alter table approval_logs add column if not exists user_id text;
alter table approval_logs add column if not exists contact_id text;
alter table approval_logs add column if not exists approval_request_id bigint;
alter table approval_logs add column if not exists action_category text;
alter table approval_logs add column if not exists status text;
alter table approval_logs add column if not exists original_message text;
alter table approval_logs add column if not exists generated_reply text;
alter table approval_logs add column if not exists reason text;
alter table approval_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table approval_logs add column if not exists created_at timestamptz not null default now();

alter table high_risk_alerts add column if not exists user_id text;
alter table high_risk_alerts add column if not exists contact_id text;
alter table high_risk_alerts add column if not exists risk_level text default 'high';
alter table high_risk_alerts add column if not exists action_category text;
alter table high_risk_alerts add column if not exists status text default 'open';
alter table high_risk_alerts add column if not exists message text;
alter table high_risk_alerts add column if not exists reason text;
alter table high_risk_alerts add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table high_risk_alerts add column if not exists created_at timestamptz not null default now();

alter table reminder_logs add column if not exists user_id text;
alter table reminder_logs add column if not exists contact_id text;
alter table reminder_logs add column if not exists reminder_text text;
alter table reminder_logs add column if not exists remind_at timestamptz;
alter table reminder_logs add column if not exists status text default 'created';
alter table reminder_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table reminder_logs add column if not exists created_at timestamptz not null default now();

alter table scheduled_message_logs add column if not exists user_id text;
alter table scheduled_message_logs add column if not exists contact_id text;
alter table scheduled_message_logs add column if not exists message text;
alter table scheduled_message_logs add column if not exists scheduled_for timestamptz;
alter table scheduled_message_logs add column if not exists status text default 'scheduled';
alter table scheduled_message_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table scheduled_message_logs add column if not exists created_at timestamptz not null default now();

alter table rag_access_logs add column if not exists user_id text;
alter table rag_access_logs add column if not exists contact_id text;
alter table rag_access_logs add column if not exists file_id text;
alter table rag_access_logs add column if not exists file_name text;
alter table rag_access_logs add column if not exists file_path text;
alter table rag_access_logs add column if not exists query text;
alter table rag_access_logs add column if not exists access_reason text;
alter table rag_access_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table rag_access_logs add column if not exists created_at timestamptz not null default now();

alter table personal_context_decision_logs add column if not exists user_id text;
alter table personal_context_decision_logs add column if not exists contact_id text;
alter table personal_context_decision_logs add column if not exists decision text;
alter table personal_context_decision_logs add column if not exists reason text;
alter table personal_context_decision_logs add column if not exists matched_rules jsonb not null default '[]'::jsonb;
alter table personal_context_decision_logs add column if not exists original_message text;
alter table personal_context_decision_logs add column if not exists final_action text;
alter table personal_context_decision_logs add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table personal_context_decision_logs add column if not exists created_at timestamptz not null default now();

create index if not exists message_logs_created_at_idx on message_logs (created_at);
create index if not exists message_logs_user_idx on message_logs (user_id);
create index if not exists agent_activity_logs_created_at_idx on agent_activity_logs (created_at);
create index if not exists agent_activity_logs_user_idx on agent_activity_logs (user_id);
create index if not exists approval_logs_created_at_idx on approval_logs (created_at);
create index if not exists approval_logs_user_idx on approval_logs (user_id);
create index if not exists high_risk_alerts_created_at_idx on high_risk_alerts (created_at);
create index if not exists high_risk_alerts_user_idx on high_risk_alerts (user_id);
create index if not exists reminder_logs_created_at_idx on reminder_logs (created_at);
create index if not exists reminder_logs_user_idx on reminder_logs (user_id);
create index if not exists scheduled_message_logs_created_at_idx on scheduled_message_logs (created_at);
create index if not exists scheduled_message_logs_user_idx on scheduled_message_logs (user_id);
create index if not exists rag_access_logs_created_at_idx on rag_access_logs (created_at);
create index if not exists rag_access_logs_user_idx on rag_access_logs (user_id);
create index if not exists personal_context_decision_logs_created_at_idx on personal_context_decision_logs (created_at);
create index if not exists personal_context_decision_logs_user_idx on personal_context_decision_logs (user_id);
