-- Persisted style profiles for global and contact-specific response styling.

create table if not exists style_profiles (
  id bigint generated by default as identity primary key,
  user_id text not null,
  contact_id text not null default 'global',
  profile_type text not null default 'contact'
    check (profile_type in ('global', 'contact')),
  traits jsonb not null default '{}'::jsonb,
  patterns jsonb not null default '[]'::jsonb,
  confidence double precision not null default 0
    check (confidence >= 0 and confidence <= 100),
  message_count integer not null default 0
    check (message_count >= 0),
  batch_count integer not null default 0
    check (batch_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep this migration safe to run against databases that already have a
-- partial style_profiles table.
alter table style_profiles add column if not exists user_id text;
alter table style_profiles add column if not exists contact_id text default 'global';
alter table style_profiles add column if not exists profile_type text default 'contact';
alter table style_profiles add column if not exists traits jsonb not null default '{}'::jsonb;
alter table style_profiles add column if not exists patterns jsonb not null default '[]'::jsonb;
alter table style_profiles add column if not exists confidence double precision not null default 0;
alter table style_profiles add column if not exists message_count integer not null default 0;
alter table style_profiles add column if not exists batch_count integer not null default 0;
alter table style_profiles add column if not exists created_at timestamptz not null default now();
alter table style_profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists style_profiles_user_contact_type_idx
  on style_profiles (user_id, contact_id, profile_type);

create index if not exists style_profiles_user_idx
  on style_profiles (user_id);

create index if not exists style_profiles_contact_idx
  on style_profiles (contact_id);

create index if not exists style_profiles_profile_type_idx
  on style_profiles (profile_type);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists style_profiles_updated_at
  on style_profiles;

create trigger style_profiles_updated_at
before update on style_profiles
for each row execute function set_updated_at();

insert into style_profiles (
  user_id,
  contact_id,
  profile_type,
  traits,
  patterns,
  confidence,
  message_count,
  batch_count
)
values (
  'default_user',
  'global',
  'global',
  '{
    "formality": {"score": 0.5, "confidence": 50},
    "politeness": {"score": 0.7, "confidence": 50},
    "verbosity": {"score": 0.5, "confidence": 50},
    "optimism": {"score": 0.5, "confidence": 50}
  }'::jsonb,
  '["neutral default style"]'::jsonb,
  50,
  0,
  0
)
on conflict (user_id, contact_id, profile_type) do nothing;
